id: t1110-password-spray-vpn-prod
name: T1110 Password Spray - VPN
query: 'fn_network_vpn_auth_failures_v1()

  | where Result == ''Failure''

  | summarize cnt = count() by SrcIP, bin(TimeGenerated, 5m)

  | where cnt > 10'
apiVersion: v1
kind: scheduledRule
metadata:
  name: t1110-password-spray-vpn-prod
  displayName: T1110 Password Spray - VPN
  owner:
    slack: '#soc-detections'
    oncall: sec-detect-oncall
    team: identity-detection
  domain: network
  lifecycle: experimental
  version: 2
  mitre_techniques:
  - T1110
  pack: network
  stable_id: 9af439bf-41d8-fc04-9a7d-a2821ad88c72
entities:
- type: Ip
  field: SrcIP
spec:
  query:
    sourceFunction: fn_network_vpn_auth_failures_v1
    where: Result == 'Failure'
    reduce: summarize cnt = count() by SrcIP, bin(TimeGenerated, 5m)
    threshold:
      operator: GreaterThan
      value: 10
      metric: cnt
  schedule:
    frequency: PT5M
    lookback: PT5M
  incident:
    severity: Medium
    createIncident: false
    grouping:
      enabled: true
      lookback: PT1H
      byEntities:
      - User
  suppression:
    enabled: true
    duration: PT1H
  enabled: true
  environments:
  - name: prod
    enabled: true
metadata_ext:
  entityMappings:
  - entityType: Ip
    fieldMappings:
    - identifier: Address
      columnName: SrcIP
